{% set version = "2.5.1" %}

package:
  name: pytest-factoryboy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-factoryboy/pytest_factoryboy-{{ version }}.tar.gz
  sha256: 7275a52299b20c0f58b63fdf7326b3fd2b7cbefbdaa90fdcfc776bbe92197484

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - poetry
  run:
    - factory_boy >=2.10.0
    - inflection
    - pytest >=5.0.0
    - python >=3.7
    - typing_extensions

test:
  imports:
    - pytest_factoryboy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pytest-factoryboy.readthedocs.io
  summary: Factory Boy support for pytest.
  license: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/pytest-dev/pytest-factoryboy

extra:
  recipe-maintainers:
    - cshaley
    - bollwyvl
